// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMzW6i7RLBWJRC8DDn2S5S87hLubnaYbc',
    appId: '1:1073356550593:web:3cfceabcc0b4c4316c7f40',
    messagingSenderId: '1073356550593',
    projectId: 'summerproject-987e0',
    authDomain: 'summerproject-987e0.firebaseapp.com',
    storageBucket: 'summerproject-987e0.appspot.com',
    measurementId: 'G-GM4D0Z1L26',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_A1vVHJVdgN6LUjN4pcbqq6lSfyxRSQs',
    appId: '1:1073356550593:android:005b20eddf4634eb6c7f40',
    messagingSenderId: '1073356550593',
    projectId: 'summerproject-987e0',
    storageBucket: 'summerproject-987e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDscG4Jzf5nuYcHny-Cr2ee8IkrCYWgw_g',
    appId: '1:1073356550593:ios:aa53d9d1d32aac796c7f40',
    messagingSenderId: '1073356550593',
    projectId: 'summerproject-987e0',
    storageBucket: 'summerproject-987e0.appspot.com',
    iosBundleId: 'com.example.summerProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDscG4Jzf5nuYcHny-Cr2ee8IkrCYWgw_g',
    appId: '1:1073356550593:ios:a9d713aff7b301a96c7f40',
    messagingSenderId: '1073356550593',
    projectId: 'summerproject-987e0',
    storageBucket: 'summerproject-987e0.appspot.com',
    iosBundleId: 'com.example.summerProject.RunnerTests',
  );
}
